<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Controllers\NotificationController.cs~RF29a027e4.TMP" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
    <PackageReference Include="MediatR.Extensions.FluentValidation.AspNetCore" Version="6.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Quartz" Version="3.18.1" />
    <PackageReference Include="Quartz.Extensions.Hosting" Version="3.18.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\sprintFlow.Application\sprintFlow.Application.csproj" />
    <ProjectReference Include="..\sprintFlow.Infrastructure\sprintFlow.Infrastructure.csproj" />
  </ItemGroup>

</Project>
