@host = https://localhost
@port = 7000
@sprintFlow.api_HostAddress = {{host}}:{{port}} 
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjE1NDkyNzE2LTAxNTUtNDhmNS05YTNkLTliMmY1NTJiMmJjYSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Im9sYUBzcHJpbnRmbG93LmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkxlYWRlciIsImV4cCI6MTc4MDgzNDk4NiwiaXNzIjoiU3ByaW50RmxvdyIsImF1ZCI6IlNwcmludEZsb3dVc2VycyJ9.QSwd8XYRMXocHHJ6J28guKJMYbBovZ4P79g25do9cDc
###
# GET all users
GET {{sprintFlow.api_HostAddress}}/api/users?role=employee&pageNumber=1&pageSize=10


###
# login
POST {{sprintFlow.api_HostAddress}}/api/login
Content-Type : application/json
{
    "email": "ola@sprintflow.com",
    "password": "P@ssw0rd!"
}
###

# Register a user
POST {{sprintFlow.api_HostAddress}}/api/identity/register
Content-Type : application/json
{
  "email" : "nounou@test.com",
  "password" : "Nounou123.",
}
###
//assign user to role
POST {{sprintFlow.api_HostAddress}}/api/identity/assignRole
Content-Type : application/json
Authorization : Bearer {{token}}
{
  "Email" : "ola@test.com",
  "Role" : "employee"
}
###
//change user role
PATCH {{sprintFlow.api_HostAddress}}/api/identity/changeRole
Content-Type : application/json
Authorization : Bearer {{token}}
{
  "Email" : "ola@test.com",
  "NewRole" : "employee"
}
###
//delete user
DELETE {{sprintFlow.api_HostAddress}}/api/identity/deleteUser
content-Type : application/json
Authorization : Bearer {{token}}
{
  "Email" : "ola@test.com"
}
###
//projects

# Create project
POST {{sprintFlow.api_HostAddress}}/api/projects/create
content-Type : application/json
Authorization : Bearer {{token}}
{
  "Name" : "project",
  "Description" : "project description"
}
###
# show all projects
GET {{sprintFlow.api_HostAddress}}/api/projects?pageNumber=1&pageSize=10
content-Type : application/json
Authorization : Bearer {{token}}
###
# show single project
GET {{sprintFlow.api_HostAddress}}/api/projects/d750ce3d-37a0-469e-b505-08de928b249c
content-Type : application/json
Authorization : Bearer {{token}}
###
# edit project
PATCH {{sprintFlow.api_HostAddress}}/api/projects/d750ce3d-37a0-469e-b505-08de928b249c
content-Type : application/json
Authorization : Bearer {{token}}
{
  "Name" : "project",
  "Description" : "project description"
}
###
GET {{sprintFlow.api_HostAddress}}/api/projects/abade627-3a79-4680-f640-08de94d57baf/tasks?pageNumber=1&pageSize=10
content-Type : application/json
Authorization : Bearer {{token}}

###
GET  {{sprintFlow.api_HostAddress}}/Test/test